/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.simple.front_back_separation;

public class Config {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        workerJNI.delete_Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum(int value) {
    workerJNI.Config_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return workerJNI.Config_num_get(swigCPtr, this);
  }

  public void setFd(boolean value) {
    workerJNI.Config_fd_set(swigCPtr, this, value);
  }

  public boolean getFd() {
    return workerJNI.Config_fd_get(swigCPtr, this);
  }

  public Config() {
    this(workerJNI.new_Config(), true);
  }

}
