/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.simple.front_back_separation;

public class workerJNI {
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
  public final static native void Config_num_set(long jarg1, Config jarg1_, int jarg2);
  public final static native int Config_num_get(long jarg1, Config jarg1_);
  public final static native void Config_fd_set(long jarg1, Config jarg1_, boolean jarg2);
  public final static native boolean Config_fd_get(long jarg1, Config jarg1_);
  public final static native long new_Config();
  public final static native void delete_Config(long jarg1);
  public final static native long GetWorker(String jarg1);
  public final static native void ReleaseWorker(long jarg1, Worker jarg1_);
  public final static native void delete_Worker(long jarg1);
  public final static native boolean Worker_Init(long jarg1, Worker jarg1_, long jarg2);
  public final static native boolean Worker_UnInit(long jarg1, Worker jarg1_);
  public final static native boolean Worker_Run(long jarg1, Worker jarg1_, long jarg2);
}
