/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.simple.front_back_separation;

public class worker {
  public static SWIGTYPE_p_int new_intp() {
    long cPtr = workerJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = workerJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    workerJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    workerJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return workerJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static Worker GetWorker(String target) {
    long cPtr = workerJNI.GetWorker(target);
    return (cPtr == 0) ? null : new Worker(cPtr, false);
  }

  public static void ReleaseWorker(Worker client) {
    workerJNI.ReleaseWorker(Worker.getCPtr(client), client);
  }

}
